### ISSUE TITLE
Xcode 5.1.1 reports "Use of undeclared identifier" won't compile

### ISSUE THREAD

**Issue by fireproof** [shi11/RemoteControls#1]
UPDATE: needed to add `#import "RemoteControls.h"` to top of /Classes/MainViewController.m (but plugin still doesn't seem to work)

This is the modification I made to MainViewController.m (hopefully per your instructions):

```
-  (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
    [[RemoteControls remoteControls]
     setWebView:self.webView];
}

- (void)remoteControlReceivedWithEvent:(UIEvent *)receivedEvent
{
    [[RemoteControls remoteControls]
     receiveRemoteEvent:receivedEvent];
}
```

**Comment by yourbuddyconner** [comment]
I've got this same issue! When trying to build my cordova project the build fails with "Use of undeclared identifier 'RemoteControls'"

It takes issue with the same block of code as posted above, mine looks identical.

**Comment by shi11** [comment]
hi, sorry, did you see his update? 

> UPDATE: needed to add #import "RemoteControls.h" to top of /Classes/MainViewController.m (but plugin still doesn't seem to work)

**Comment by yourbuddyconner** [comment]
Is that what you did in your implementation to get it working? It seemed as though he didn't have much success doing that so I wasn't sure.

**Comment by shi11** [comment]
Yup, if you're seeing the "undeclared intentifier" error than declaring it by importing the RemoteControls.h file should solve that problem.
