### ISSUE TITLE
Metadata Help

### ISSUE THREAD

**Issue by latesnacker** [shi11/RemoteControls#13]
I cannot get the metadata working

I am using the same code below but I cannot get the metas to work. When I run the app in the ios simulator and watch the console, updateMetas never returns either a success or a fail. What can I be doing wrong that this function never returns and doesn't throw any errors?

```javascript
console.log(window.remoteControls); //not undefined

var params = [artist, title, album, image, duration, elapsedTime];
  window.remoteControls.updateMetas(function(success){
      console.log(success);
  }, function(fail){
      console.log(fail);
  }, params);
```

**Comment by shi11** [comment]
could be a few things. 
- make sure you are waiting for until after the deviceready event.
- make sure the plugin is installed...cordova plugin add com.rd11.remote-controls

**Comment by LukePulverenti** [comment]
If by chance you're using the telerik wkwbeview plugin, it doesn't work with that.

**Comment by latesnacker** [comment]
Thank you for the super quick response from both of you.

I am not explicitly waiting for deviceready, but this function only occurs after the user clicks on a button, so that shouldn't be the problem, correct? Also, I am not using the wkwebview plugin.

The plugin is definitely installed, I can even see the remote events getting logged in xCode when I hit the skip button, but I cannot seem to get the metadata to be correct.

**Comment by shi11** [comment]
can you share an example of what your metadata looks like? Sometimes if the
metadata isn't perfect, it doesn't show up...

**Comment by latesnacker** [comment]
the exact code looks like this:
```javascript
var params = ["Joespin", _this.currentSong.song.title, playlist.title, playlist.albumPicture, 180, 5];
                            window.remoteControls.updateMetas(function (success) {
                                console.log(success);
                            }, function (fail) {
                                console.log(fail);
                            }, params);
```
right before this line, the values of these variables are (this isn't the code, this is debug view of the values):
_this.currentSong.song.title = "Miami Lockdown"
playlist.title = "Rockin' Pop Moods"
playlist.albumPicture = "https://joespinstorage.blob.core.windows.net/thumbnails/rockin_pop_moods.jpg"

**Comment by latesnacker** [comment]
Also, here is what the lockscreen looks like on the emulator. The long text is the url of file that is playing, which of course should be the song name.

https://onedrive.live.com/redir?resid=881C574E25663841!220126&authkey=!ANMfWatBns5lads&v=3&ithint=photo%2cpng

**Comment by shi11** [comment]
couple thoughts, try removing the single quote in Rockin'. Also check that
albumPicture - the link didn't work for me.

**Comment by latesnacker** [comment]
Using the code from the readme, I was able to get the metadata set on the launch of the application. But once I play html5 audio, that metadata is overwritten. It does not seem that I can change the metadata while playing audio. I have tried setting the metadata (using the same code from the readme) before and after the audio is set, but either way the metadata is either never set or seems to be overwritten by the html5 audio url.

Is this expected behavior?

**Comment by shi11** [comment]
Ah ok, sorry I haven't tested it yet with html5 audio. I've been using the Media plugin. I do think that OS overrides metadata when using html5. Check out this fork: https://github.com/ghenry22/RemoteControls - he made a change for html5 audio - maybe he can help?
