### ISSUE TITLE
Build is failing with Cordova 5.1, cordova-ios 3.8

### ISSUE THREAD

**Issue by mhartington** [shi11/RemoteControls#15]
Not sure if I'm missing anything, but I'm not able to build after editing my `MainViewController.m`

Starting at line74

http://pastebin.com/kubGzc94

Here's the output form my cordova build 

```
/Users/mhartington/GitHub/ionic/tmp/platforms/ios/tmp/Classes/MainViewController.m:79:7: error: use of undeclared identifier 'RemoteControls'
    [[RemoteControls remoteControls] setWebView:self.webView];
      ^
/Users/mhartington/GitHub/ionic/tmp/platforms/ios/tmp/Classes/MainViewController.m:93:10: error: use of undeclared identifier 'RemoteControls'
       [[RemoteControls remoteControls] receiveRemoteEvent:receivedEvent];
         ^
```

**Comment by shi11** [comment]
hmm, what's the error when you build in XCode? Maybe RemoteControls.m needs to be added to Build Phases > Compiled Sources ?

**Comment by mhartington** [comment]
The actual error in Xcode is `Use of undeclared identifier 'RemoteControls'`

**Comment by shi11** [comment]
I think you're missing `#import "RemoteControls.h"` which should be below `#import "MainViewController.h"`

**Comment by mhartington** [comment]
Cool, just made a PR to mention it in the docs.
https://github.com/shi11/RemoteControls/pull/16
