### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by philip65** [shi11/RemoteControls#22]
Hi,
When I try to compile after modify the MainViewController.m
I have this error in MainViewController.m : 
"No visible @interface for 'RemoteControls' declares the selector 'setWebView:'

and this error in RemoteControls.m : 
"No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

in the - (void)receiveRemoteEvent:(UIEvent *)receivedEvent function .

Please help me I'm don't find any solutions.

Thanks

**Comment by shi11** [comment]
Are you importing RemoteControls.h? See the Readme.

`#import "RemoteControls.h"`

**Comment by philip65** [comment]
Yes I do everything in Readme

**Comment by shi11** [comment]
I'm not sure, perhaps this will point you in the right direction, http://stackoverflow.com/questions/10387330/no-visible-interface-for

**Comment by kylesziv** [comment]
I'm actually getting this error too.

**Comment by philip65** [comment]
I worked for some fix but no result, I need to release the app quickly to my client
Can you help me please ?
Thanks

**Comment by shi11** [comment]
Can you both please share more details about your environment.

**Comment by philip65** [comment]
I work on : 
Cordova CLI: 6.0.0
OS: Mac OS X El Capitan
Node Version: v4.2.6
Xcode version: Xcode 7.3 Build version 7D141l (for Xcode I have 7.3 & 7.2)

Ask me if you need more informations.
Thanks

**Comment by shi11** [comment]
What version of iOS are you compiling against?

**Comment by philip65** [comment]
iOS 9.2

**Comment by shi11** [comment]
Ok apparently this is an issue with cordova ios@4.0.0 and up. 

This is the temp fix: 
`cordova platform remove ios
cordova platform add ios@3.9.2`

This issue helped me find the answer: https://github.com/Telerik-Verified-Plugins/PushNotification/issues/71

**Comment by ghenry22** [comment]
Looks like the self.webview statements in the ios code and those added to the mainviewcontroller.m cause it to throw up.  I have a fork of the plugin updated in a similar way to the linked post and that is fine but I don't know how to handle the self.webview statements that are added into the mainviewcontroller.m file?

Any thoughts?

**Comment by jcesarmobile** [comment]
My pull request should fix the issue
https://github.com/shi11/RemoteControls/pull/23

**Comment by ghenry22** [comment]
I have done a first test with IOS@4.1.0 and the updated plugin as per PR #23 and all works correctly in the emulator.  I will test on a real device later today when I have access to a spare IOS device.

**Comment by ghenry22** [comment]
Huge thank you to @jcesarmobile !

**Comment by shi11** [comment]
Finally closing this issue. Big thanks @jcesarmobile !!
