### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by abuturla** [shi11/RemoteControls#27]
Installing via:
cordova plugin add com.rd11.remote-controls

results in the following error:
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.rd11.remote-controls

**Comment by stephanebachelier** [comment]
@abuturla use the git url

`cordova plugin add https://github.com/shi11/RemoteControls.git`

**Comment by alexlopezit** [comment]
This is still an issue with cordova 7.0.1 and node 8.4, looks like the installation requires a "'package.json" file which is missing from this plugin

**Comment by shi11** [comment]
sorry for that (and for the inactivity maintaining this plugin). 
I just published the plugin to npm - that command should work now. https://www.npmjs.com/package/com.rd11.remote-controls

**Comment by alexlopezit** [comment]
Awesome, thanks so much @shi11 , keep up the good work!
