### ISSUE TITLE
How to use it in Intel XDK?

### ISSUE THREAD

**Issue by pouriaMaleki** [shi11/RemoteControls#4]
Hey man,

I'm developing in windows so I have to use Intel XDK to build iOS versions.

How I can add it into XKD plugins?

btw, Thank you for your awesome plugin.

**Comment by shi11** [comment]
Hey there, sorry for the slow response. did you figure it out? i'm not familiar with intel xdk but perhaps this documentation can lead you in the right direction. https://software.intel.com/en-us/html5/articles/using-the-cordova-for-android-ios-etc-build-option

**Comment by pouriaMaleki** [comment]
No problem, In fact the reason I used XDK is I don't have Mac and for other reasons I have to get one, I'll use native cordova on Mac :) :+1:
