### ISSUE TITLE
Not able to advance after instructions

### ISSUE THREAD

**Issue by yuujinlee** [shi11/RemoteControls#5]
Hello, 

Sorry for adding this as an issue, I could not find a way to contact you.  This is a great plugin, I am just cannot get it to work for me.  I am fairly new to Cordova, and having a tough time figuring out what to do with the codes you provided. I followed your steps in your instructions, but the code you provided, no clue what to do there!

    function onDeviceReady() {
      artist = "Daft Punk";
      title = "One More Time";
      album = "Discovery";
      image = "path_within_documents_storage";
      elapsedTime = my_media.getDuration();

      var params = [artist, title, album, image,  elapsedTime];
      window.plugins.remoteControls.updateMetas(function(success){
          console.log(success);
      }, function(fail){
          console.log(fail);
      }, params);
    }

    //listen for the event 
    document.addEventListener("remote-event", function(event) {
    //do something
    })

In my app.js, this is how I am displaying the data from a $http request

    .controller('MainCtrl', function($scope, $http, $interval) {
          // $interval(function(){

          $http({method: 'get', url: 'http://metaphor.goomradio.com/now/9594145/limit/1?whitelist=1.jsonp'}).
                      success(function(data, status, headers, config) {
                        // this callback will be called asynchronously
                        // when the response is available
                   
                       var title = data.results[0].title;
                       var artist = data.results[0].artist;
                       var cover = data.results[0].cover_url;
                       console.log(title);
                       console.log(artist);
                       console.log(cover);
                       document.getElementById('title').innerText = title;
                       document.getElementById('artist').innerText = artist;
                       document.getElementById('jacket').style.background = 'url('+cover+')';

                      }).
                      error(function(data, status, headers, config) {
                        // called asynchronously if an error occurs
                        // or server returns response with an error status.
                        console.log('not working');
                      });
          // },10000);
  
    })

Any help would be great!

**Comment by shi11** [comment]
perhaps post something on stackoverflow.com? this isn't an issue so i'm closing it.
