### ISSUE TITLE
play/pause resets song info

### ISSUE THREAD

**Issue by tomaszrondio** [shi11/RemoteControls#6]
When I click play or pause button on locked screen it stops/starts playing but also resets song information. 
Also home button removes both controls and song info. 

BTW: I had to import remoteControls.h in MainViewController to make it work.

**Comment by shi11** [comment]
Thnx Tomasz!

- Play/Pause resetting song info is a bug. 
- Home button hides controls is intended behavior I think. Press it again and the controls return.
- Will add import remoteControls.h to readme.

**Comment by tomaszrondio** [comment]
+ play/pause thing
It happens because js Audio element stops playing and it "overwrites" RemoteControls song info. Workaround is to updateMetas again using timeout.

**Comment by greatwitenorth** [comment]
@tomaszrondio I had the same issue. Just did the updateMetas on pause events. It's too bad though cause the URL still flashes for a moment when using the >> button to skip a song. Is there any way around this?

**Comment by tomaszrondio** [comment]
It also flashes in my app. I haven't found good solution for that.

**Comment by pvandrunen** [comment]
I set the metadata to update on the play/pause listeners but here again I have the temporary flash of the file URL, it doesn't, however, flash when I hit the next/previous buttons.

**Comment by greatwitenorth** [comment]
@pvandrunen I'm seeing the same thing. The only way around it so far is to implement audio natively. The only library out there that has this is [PlayerHater](https://github.com/wnyc/cordova-plugin-playerhater) but in my experience it's very buggy and not currently compiling properly on iOS or Android.

**Comment by pvandrunen** [comment]
Thanks @greatwitenorth, I will live with the temporary flash when pausing/playing over compile issues and bugs.

**Comment by pvandrunen** [comment]
I noticed on YouTube that the slide-up controls in iOS display the title attribute in the <video> tag. I'm going to see if this is something that can be done with the audio element.
Check the source code here:
https://m.youtube.com/watch?v=J8H_XBBNMXM
title="A Charlie Brown's Christmas Tales"

**Comment by LukePulverenti** [comment]
Just to confirm - you guys are using a plain html audio element?

**Comment by pvandrunen** [comment]
We are using a custom built js audio player, like this:
<code>this.myaudio = new Audio(myaudioURL);</code>

**Comment by greatwitenorth** [comment]
I have a similar setup to @pvandrunen

**Comment by LukePulverenti** [comment]
Right, you have a custom api, but what is your underlying playback method? html audio tag? WebAudio? a native player?

**Comment by greatwitenorth** [comment]
I'm using an HTML audio tag.

-- 
Best regards,

Nick Verwymeren
204-951-3712
www.nickv.codes
Skype: greatwitenorth
