### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by jambots** [shi11/RemoteControls#7]
On Phonegap Build 3.7.0 I'm getting 'Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.' Is this replicable by anyone else using Build?

**Comment by shi11** [comment]
Hi, I haven't seen that one and I test on an iphone 5S (arm64).

**Comment by jambots** [comment]
My understanding is that Build is complying with Apple requirements. Have you uploaded an app with your plugin since the change?
http://community.phonegap.com/nitobi/topics/apple-forces-ios-8-sdk-and-64-bit

**Comment by shi11** [comment]
I've uploaded an app to testflight beta. Are you sure the error is caused by this plugin?

**Comment by vespino** [comment]
Same error here: "Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture. - You can fix this here". Too bad, I would love to use it in my project.

**Comment by shi11** [comment]
Sorry to hear. Where are you receiving this error? In XCode? I mainly use Ionic not Phonegap, however I just updated Phonegap to version 5.0.0, created a HelloWorld project and added this plugin. It ran it without this error. 

Perhaps trying updating Phonegap to 5.0.0 and see if you still get the error?

**Comment by vespino** [comment]
I'm using Phonegap Build.

**Comment by jambots** [comment]
When was the plugin compiled last? The 64-bit requirement for new apps added to the store began February 1st, 2015.  A specific test would be  to create a new app and use the App Loader to upload an IPA with the plugin included. If that proves the plugin is 64-bit then the error must be caused by phonegap build.

**Comment by vespino** [comment]
Last time would be 13 days ago ;)
