### ISSUE TITLE
Ability clear media info

### ISSUE THREAD

**Issue by bionik** [shi11/RemoteControls#8]
Is there a way to clear media info on lockscreen?

Something like window.remoteControls.clearMetas()

**Comment by shi11** [comment]
There's isn't a specific function like clearMetas() at the moment, Lauri. What may work as a temp fix, is to use updateMetas() and pass empty strings.

Feel free to add clearMetas() and do a pull request ;)

**Comment by alisonmonteiro** [comment]
@shi11 I'll try to add the clearMetas().

But now I'm trying to do something like [this](https://github.com/homerours/cordova-music-controls-plugin/blob/master/www/MusicControls.js#L36) but nothing works. Any idea?

**Comment by shi11** [comment]
@alisonmonteiro there isn't but what is it you're trying to do? toggle play/pause? I think this should happen automatically if you're using the Media plugin.

**Comment by alisonmonteiro** [comment]
@shi11 Thank you for the super quick response.

I'm using an iPhone 6 with iOS 9.2 and it's doesn't happen automatically. :/
Objective C is so hard but I've forked this repo and try a lot of thinks. :muscle: 

Now I think this works. Take a look at [this file](https://github.com/1line/RemoteControls/blob/master/src/ios/RemoteControls.m).

(Sorry for my bad english) :-1:

**Comment by shi11** [comment]
Yeah honestly I'm not an Obj-C expert either. Glad you figured it out.
