### ISSUE TITLE
Remote controls action from app

### ISSUE THREAD

**Issue by andreafalco** [shi11/RemoteControls#9]
Hi,
is there a way to play/pause, next/prev song by send remote controls from app?

I would like to change/play/skip/pause song from my cordova app if some event happen. For example if a press a button on my view, i would like to start play music from ios music app.

Thanks in advance,
Andri

**Comment by shi11** [comment]
Have you researched using the Cordova Media plugin? Unless I'm not understanding what you're trying to do - as long as you have the location of the file that you'd like to play, you should be able to start playing it through this plugin: http://docs.phonegap.com/en/edge/cordova_media_media.md.html

**Comment by andreafalco** [comment]
Thanks for the response, but this is not what i'm looking for. I try to explain my problem. 

In my device i have some music added to itunes library and i listen this music through standard ios music app. I created a cordova app to manage music and my problem is: how can i play/pause/stop or skip songs from my cordova app? Can i send something like "remote controls" from my cordova application?

Thanks in advance,
Andri

**Comment by shi11** [comment]
No problem. RemoteControls won't work in that case. I'm not sure if there's a cordova plugin for what you're looking for, but it's probably possible. You should research controlling this ios class: MPMusicPlayerController. Hope that helps!
